apiVersion: v1
kind: Service
metadata:
  name: spam-classifier-service
spec:
  selector:
    app: spam-classifier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer  # Use LoadBalancer if deploying to a cloud provider, NodePort for local testing
